### ISSUE TITLE
ReferenceError: Console is not defined

### ISSUE THREAD

**Issue by HectorRPL** [scotch-io/meteor-slack#8]
Hello I clone this repository.... and I have error.
Some ideas?
```
C:\meteor-slack>dir

 Directorio de C:\meteor-slack

04/01/2017  12:25 p. m.    <DIR>          .
04/01/2017  12:25 p. m.    <DIR>          ..
04/01/2017  12:25 p. m.    <DIR>          .meteor
04/01/2017  12:25 p. m.    <DIR>          client
04/01/2017  12:25 p. m.    <DIR>          lib
04/01/2017  12:25 p. m.               173 README.md
04/01/2017  12:25 p. m.    <DIR>          server
               1 archivos            173 bytes
               6 dirs  43,754,393,600 bytes libres

C:\meteor-slack>meteor --port 3001
[[[[[ C:\meteor-slack ]]]]]

=> Started proxy.
=> Started MongoDB.

C:\Users\*****\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:643
      Console.debug(err);
      ^
ReferenceError: Console is not defined
    at Object._onImmediate (C:\Users\*****\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:643:7)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

C:\meteor-slack>_

```

My  procedure was:
```
$ git clone https://github.com/scotch-io/meteor-slack.git
$ cd meteor-slack
$ meteor --port 3001
```

**Comment by HectorRPL** [comment]
I try 3 times:

`$ meteor`
And no more error messages.

Thanks.

**Comment by d4nyll** [comment]
Hi @HectorRPL, haven't worked with Meteor on Windows, but it looks like it's a bug in the Meteor tools itself, maybe a dependency wasn't met?
