### ISSUE TITLE
Exception while invoking method 'createUser'

### ISSUE THREAD

**Issue by HectorRPL** [scotch-io/meteor-slack#9]
Hello 
In this repository I put my email in register new user, but the message was this:

```
Exception while invoking method 'createUser' AuthError: Invalid login - 435 4.7.8 Error: authentication failed:
    at Object.Future.wait (C:\Users\*****\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15

    at smtpSend (packages/email/email.js:76:1)
    at Object.Email.send (packages/email/email.js:153:1)
    at Object.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:627:1)
    at packages/accounts-password/password_server.js:748:1
    at tryLoginMethod (packages/accounts-base/accounts_server.js:161:1)
    at Object.Accounts._loginMethod (packages/accounts-base/accounts_server.js:277:1)
    at [object Object].Meteor.methods.createUser (packages/accounts-password/password_server.js:724:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    - - - - -
    at SMTPClient._actionAUTHComplete (C:\Users\*****\AppData\Local\.meteor\packages\email\1.0.6\npm\node_modules\simplesmtp\lib\client.js:826:23)
    at SMTPClient._onData (C:\Users\*****\AppData\Local\.meteor\packages\email\1.0.6\npm\node_modules\simplesmtp\lib\client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:442:13)
```

some ideas?

**Comment by d4nyll** [comment]
After you clone the repository, you should create your own transactional email account (with a service like Mailgun), and replace your credentials in [`server/mail.js`](https://github.com/scotch-io/meteor-slack/blob/master/server/mail.js).
